.TH "InputParametrs.cpp" 3 "Tue Mar 28 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputParametrs.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'InputParametrs\&.h'\fP
.br
\fC#include 'def_values\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
