.TH "InputParametrs.h" 3 "Tue Mar 28 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputParametrs.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'WifiManager\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInputParametrs\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
