.TH "InputParametrs" 3 "Tue Mar 28 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputParametrs
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InputParametrs\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputParametrs\fP (char **argv, int argc)"
.br
.ti -1c
.RI "int \fBdo_cmd\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InputParametrs::InputParametrs (char ** argv, int argc)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int InputParametrs::do_cmd ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
