.TH "main.cpp" 3 "Tue Mar 28 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'WifiManager\&.h'\fP
.br
\fC#include 'InputParametrs\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmy_exit\fP ()"
.br
.ti -1c
.RI "void \fBerr_code_parser\fP (int err_code)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void err_code_parser (int err_code)"

.SS "int main (int argc, char ** argv)"

.SS "void my_exit ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
