.TH "old vers.cpp" 3 "Tue Mar 28 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
old vers.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBSIO_Errors\fP \fBSIO_Errors_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSIO_Errors\fP { \fBERROR_NO\fP = 0x00, \fBERROR_01\fP, \fBERROR_02\fP, \fBERROR_GPIO_INIT\fP, \fBERROR_UNKNOWN_COMMAND\fP, \fBERROR_CRC\fP, \fBERROR_RELAY_NOT_FOUND\fP, \fBUSAGE_ERROR\fP, \fBARGUMENT_ERROR\fP, \fBRESOURCE_BUSY_ERROR\fP, \fBINTERNAL_ERROR\fP, \fBWRONG_ESSID\fP, \fBWRONG_PASSWORD\fP }"
.br
.ti -1c
.RI "enum \fBIP\fP { \fBIP0\fP = 0, \fBIP128\fP = 128, \fBIP192\fP = 192, \fBIP224\fP = 224, \fBIP240\fP = 240, \fBIP248\fP = 248, \fBIP252\fP = 252, \fBIP254\fP = 254, \fBIP255\fP = 255 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBSIO_Errors\fP \fBSIO_Errors_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBIP\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIP0 \fP\fP
.TP
\fB\fIIP128 \fP\fP
.TP
\fB\fIIP192 \fP\fP
.TP
\fB\fIIP224 \fP\fP
.TP
\fB\fIIP240 \fP\fP
.TP
\fB\fIIP248 \fP\fP
.TP
\fB\fIIP252 \fP\fP
.TP
\fB\fIIP254 \fP\fP
.TP
\fB\fIIP255 \fP\fP
.SS "enum \fBSIO_Errors\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIERROR_NO \fP\fP
.TP
\fB\fIERROR_01 \fP\fP
.TP
\fB\fIERROR_02 \fP\fP
.TP
\fB\fIERROR_GPIO_INIT \fP\fP
.TP
\fB\fIERROR_UNKNOWN_COMMAND \fP\fP
.TP
\fB\fIERROR_CRC \fP\fP
.TP
\fB\fIERROR_RELAY_NOT_FOUND \fP\fP
.TP
\fB\fIUSAGE_ERROR \fP\fP
.TP
\fB\fIARGUMENT_ERROR \fP\fP
.TP
\fB\fIRESOURCE_BUSY_ERROR \fP\fP
.TP
\fB\fIINTERNAL_ERROR \fP\fP
.TP
\fB\fIWRONG_ESSID \fP\fP
.TP
\fB\fIWRONG_PASSWORD \fP\fP
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
