pragma Singleton

import QtQuick

QtObject {
    readonly property string triangleExclamation:               "\uf071"
    readonly property string bell:                              "\uf0f3"
    readonly property string xmark:                             "\uf00d"
    readonly property string circleXmark:                       "\uf057"
    readonly property string gear:                              "\uf013"
    readonly property string signalStream:                      "\uf8dd"
    readonly property string droplet:                           "\uf043"
    readonly property string fan:                               "\uf863"
    readonly property string circleCheck:                       "\uf058"
    readonly property string sun:                               "\uf185"
    readonly property string sunDust:                           "\uf764"
    readonly property string bolt:                              "\uf0e7"
    readonly property string bellExclamation:                   "\uf848"
    readonly property string calendarDays:                      "\uf073"
    readonly property string wrench:                            "\uf0ad"
    readonly property string wifi:                              "\uf1eb"
    readonly property string arrowsRotate:                      "\uf021"
    readonly property string circleInfo:                        "\uf05a"
    readonly property string memoCircleInfo:                    "\ue49a"
    readonly property string link:                              "\uf0c1"
    readonly property string eyeSlash:                          "\uf070"
    readonly property string eye:                               "\uf06e"
    readonly property string check:                             "\uf00c"
    readonly property string arrowRight:                        "\uf061"
    readonly property string circlePlay:                        "\uf144"
    readonly property string fileExclamation:                   "\uf31a"
    readonly property string clockThree:                        "\ue356"
    readonly property string circlePhone:                       "\ue11b"
    readonly property string globePointer:                      "\ue60e"
    readonly property string globe:                             "\uf0ac"
    readonly property string briefcase:                         "\uf0b1"
    readonly property string headSet:                           "\uf590"
    readonly property string grid2Plus:                         "\ue197"
    readonly property string calendarClock:                     "\ue0d2"
    readonly property string penCircle:                         "\ue20e"
    readonly property string revert:                            "\uf01e"
    readonly property string download:                          "\uf019"
    readonly property string restart:                           "\uf0e2"
    readonly property string night:                             "\uf186"
}
