image: atlassian/default-image:3

pipelines:
  branches:
    master:
      - step: 
          name: Install software
          script:
            - apt update && apt install -y g++-arm-linux-gnueabihf
            - cd src
            - arm-linux-gnueabihf-g++ crc.c Luminosity_report.cpp  Peripheral.cpp serial_drv.c -o Luminosity.out
          artifacts:
            - src/Luminosity.out
      - step:
          name: Artifactory connection
          script:
            - pipe: jfrog/jfrog-setup-cli:2.0.0
            - source ./jfrog-setup-cli.sh
            - jf rt ping
            - jf rt u src/Luminosity.out nuve1-Luminosity/v${BITBUCKET_BUILD_NUMBER}/Luminosity.out
            - jf rt u src/Luminosity.out nuve1-Luminosity/latest/Luminosity.out
